In [1]:
import numpy as np
    

In [2]:
def get_power(array, power):
    result = np.power(array, power)
    #print array + ' to the ' + power + ': ' + result
    print '%s to the %d: %s' % (str(array), power, str(result))
    return result

In [3]:
def get_sum(array):
    result = np.sum(array)
    print 'sum of %s: %s' % (str(array), str(result))
    return result

In [4]:
def get_subtraction(array1, array2):
    result = np.subtract(array1, array2)
    print 'subtraction of %s and %s: %s' % (str(array1), str(array2), str(result))
    return result

In [5]:
def get_product(array1, array2):
    result = np.multiply(array1, array2)
    print 'product of %s and %s: %s' % (str(array1), str(array2), str(result))
    return result

In [6]:
def get_euclidean_distance(array1, array2):
    sub = get_subtraction(array1, array2)
    power = get_power(sub, 2)
    sum_power = get_sum(power)
    return np.sqrt(sum_power)

In [7]:
def get_cosine_similarity(array1, array2):
    den_1 = np.sqrt(get_sum(get_power(array1, 2)))
    den_2 = np.sqrt(get_sum(get_power(array2, 2)))
    den = den_1 * den_2
    num = get_sum(get_product(array1, array2))
    return num / den

In [8]:
dp_a = [1., 2.]
dp_b = [3., 5.]
dp_c = [5., 4.]

In [9]:
print get_cosine_similarity(dp_a, dp_b)
print get_cosine_similarity(dp_a, dp_c)
print get_cosine_similarity(dp_b, dp_c)

[1.0, 2.0] to the 2: [ 1.  4.]
sum of [ 1.  4.]: 5.0
[3.0, 5.0] to the 2: [  9.  25.]
sum of [  9.  25.]: 34.0
product of [1.0, 2.0] and [3.0, 5.0]: [  3.  10.]
sum of [  3.  10.]: 13.0
0.997054485502
[1.0, 2.0] to the 2: [ 1.  4.]
sum of [ 1.  4.]: 5.0
[5.0, 4.0] to the 2: [ 25.  16.]
sum of [ 25.  16.]: 41.0
product of [1.0, 2.0] and [5.0, 4.0]: [ 5.  8.]
sum of [ 5.  8.]: 13.0
0.9079593845
[3.0, 5.0] to the 2: [  9.  25.]
sum of [  9.  25.]: 34.0
[5.0, 4.0] to the 2: [ 25.  16.]
sum of [ 25.  16.]: 41.0
product of [3.0, 5.0] and [5.0, 4.0]: [ 15.  20.]
sum of [ 15.  20.]: 35.0
0.93742527201


In [10]:
print get_euclidean_distance(dp_a, dp_b)
print get_euclidean_distance(dp_a, dp_c)
print get_euclidean_distance(dp_b, dp_c)

subtraction of [1.0, 2.0] and [3.0, 5.0]: [-2. -3.]
[-2. -3.] to the 2: [ 4.  9.]
sum of [ 4.  9.]: 13.0
3.60555127546
subtraction of [1.0, 2.0] and [5.0, 4.0]: [-4. -2.]
[-4. -2.] to the 2: [ 16.   4.]
sum of [ 16.   4.]: 20.0
4.472135955
subtraction of [3.0, 5.0] and [5.0, 4.0]: [-2.  1.]
[-2.  1.] to the 2: [ 4.  1.]
sum of [ 4.  1.]: 5.0
2.2360679775


In [11]:
import graphlab

important_words = ['the', 'a', 'quick', 'brown', 'fox', 'jumps', 'over', 'lazy', 'dog', 'outpaces']

# Remote punctuation
def remove_punctuation(text):
    import string
    return text.lower().translate(None, string.punctuation) 

import graphlab
from graphlab import SFrame

sentences = graphlab.SFrame({'value':['The quick brown fox jumps over the lazy dog.', 'A quick brown dog outpaces a quick fox.']})
print sentences

sentences['clean'] = sentences['value'].apply(remove_punctuation)

# Split out the words into individual columns
for word in important_words:
    sentences[word] = sentences['clean'].apply(lambda s : s.split().count(word))
    
print sentences

[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: /tmp/graphlab_server_1473107887.log
INFO:graphlab.cython.cy_server:GraphLab Create v2.1 started. Logging: /tmp/graphlab_server_1473107887.log


This non-commercial license of GraphLab Create for academic use is assigned to pvcastro@gmail.com and will expire on September 03, 2017.
+-------------------------------+
|             value             |
+-------------------------------+
| The quick brown fox jumps ... |
| A quick brown dog outpaces... |
+-------------------------------+
[2 rows x 1 columns]

+-------------------------------+-------------------------------+-----+---+-------+
|             value             |             clean             | the | a | quick |
+-------------------------------+-------------------------------+-----+---+-------+
| The quick brown fox jumps ... | the quick brown fox jumps ... |  2  | 0 |   1   |
| A quick brown dog outpaces... | a quick brown dog outpaces... |  0  | 2 |   2   |
+-------------------------------+-------------------------------+-----+---+-------+
+-------+-----+-------+------+------+-----+----------+
| brown | fox | jumps | over | lazy | dog | outpaces |
+-------+-----+-------+

In [12]:
values = sentences[important_words].to_numpy()
sentence_1 = values[0]
sentence_2 = values[1]
print get_euclidean_distance(sentence_1, sentence_2)
print 1 - get_cosine_similarity(sentence_1, sentence_2)

subtraction of [2 0 1 1 1 1 1 1 1 0] and [0 2 2 1 1 0 0 0 1 1]: [ 2 -2 -1  0  0  1  1  1  0 -1]
[ 2 -2 -1  0  0  1  1  1  0 -1] to the 2: [4 4 1 0 0 1 1 1 0 1]
sum of [4 4 1 0 0 1 1 1 0 1]: 13
3.60555127546
[2 0 1 1 1 1 1 1 1 0] to the 2: [4 0 1 1 1 1 1 1 1 0]
sum of [4 0 1 1 1 1 1 1 1 0]: 11
[0 2 2 1 1 0 0 0 1 1] to the 2: [0 4 4 1 1 0 0 0 1 1]
sum of [0 4 4 1 1 0 0 0 1 1]: 12
product of [2 0 1 1 1 1 1 1 1 0] and [0 2 2 1 1 0 0 0 1 1]: [0 0 2 1 1 0 0 0 1 0]
sum of [0 0 2 1 1 0 0 0 1 0]: 5
0.564805860111


In [13]:
sentences

Columns:
	value	str
	clean	str
	the	int
	a	int
	quick	int
	brown	int
	fox	int
	jumps	int
	over	int
	lazy	int
	dog	int
	outpaces	int

Rows: 2

Data:
+-------------------------------+-------------------------------+-----+---+-------+
|             value             |             clean             | the | a | quick |
+-------------------------------+-------------------------------+-----+---+-------+
| The quick brown fox jumps ... | the quick brown fox jumps ... |  2  | 0 |   1   |
| A quick brown dog outpaces... | a quick brown dog outpaces... |  0  | 2 |   2   |
+-------------------------------+-------------------------------+-----+---+-------+
+-------+-----+-------+------+------+-----+----------+
| brown | fox | jumps | over | lazy | dog | outpaces |
+-------+-----+-------+------+------+-----+----------+
|   1   |  1  |   1   |  1   |  1   |  1  |    0     |
|   1   |  1  |   0   |  0   |  0   |  1  |    1     |
+-------+-----+-------+------+------+-----+----------+
[2 rows x 12 columns]

In [14]:
sentences = sentences.add_row_number()
sentences

Columns:
	id	int
	value	str
	clean	str
	the	int
	a	int
	quick	int
	brown	int
	fox	int
	jumps	int
	over	int
	lazy	int
	dog	int
	outpaces	int

Rows: 2

Data:
+----+-------------------------------+-------------------------------+-----+---+
| id |             value             |             clean             | the | a |
+----+-------------------------------+-------------------------------+-----+---+
| 0  | The quick brown fox jumps ... | the quick brown fox jumps ... |  2  | 0 |
| 1  | A quick brown dog outpaces... | a quick brown dog outpaces... |  0  | 2 |
+----+-------------------------------+-------------------------------+-----+---+
+-------+-------+-----+-------+------+------+-----+----------+
| quick | brown | fox | jumps | over | lazy | dog | outpaces |
+-------+-------+-----+-------+------+------+-----+----------+
|   1   |   1   |  1  |   1   |  1   |  1   |  1  |    0     |
|   2   |   1   |  1  |   0   |  0   |  0   |  1  |    1     |
+-------+-------+-----+-------+------+------+-----+----------+
[2 rows x 13 columns]

In [15]:
sentences['tf_idf'] = graphlab.text_analytics.tf_idf(sentences['clean'])
sentences

Columns:
	id	int
	value	str
	clean	str
	the	int
	a	int
	quick	int
	brown	int
	fox	int
	jumps	int
	over	int
	lazy	int
	dog	int
	outpaces	int
	tf_idf	dict

Rows: 2

Data:
+----+-------------------------------+-------------------------------+-----+---+
| id |             value             |             clean             | the | a |
+----+-------------------------------+-------------------------------+-----+---+
| 0  | The quick brown fox jumps ... | the quick brown fox jumps ... |  2  | 0 |
| 1  | A quick brown dog outpaces... | a quick brown dog outpaces... |  0  | 2 |
+----+-------------------------------+-------------------------------+-----+---+
+-------+-------+-----+-------+------+------+-----+----------+
| quick | brown | fox | jumps | over | lazy | dog | outpaces |
+-------+-------+-----+-------+------+------+-----+----------+
|   1   |   1   |  1  |   1   |  1   |  1   |  1  |    0     |
|   2   |   1   |  1  |   0   |  0   |  0   |  1  |    1     |
+-------+-------+-----+-------+------+------+-----+----------+
+-------------------------------+
|             tf_idf            |
+-------------------------------+
| {'brown': 0.0, 'lazy': 0.6... |
| {'outpaces': 0.69314718055... |
+-------------------------------+
[2 rows x 14 columns]

In [19]:
from scipy.sparse import csr_matrix
def sframe_to_scipy(column):
    print 'Parameter:'
    print column
    """ 
    Convert a dict-typed SArray into a SciPy sparse matrix.
    
    Returns
    -------
        mat : a SciPy sparse matrix where mat[i, j] is the value of word j for document i.
        mapping : a dictionary where mapping[j] is the word whose values are in column j.
    """
    # Create triples of (row_id, feature_id, count).
    x = graphlab.SFrame({'X1':column})
    print 'Creating X1:'
    print x
    
    # 1. Add a row number.
    x = x.add_row_number()
    print 'Adding row number:'
    print x
    # 2. Stack will transform x to have a row for each unique (row, key) pair.
    x = x.stack('X1', ['feature', 'value'])
    print 'Pairs of word and tf-idf:'
    print x

    # Map words into integers using a OneHotEncoder feature transformation.
    f = graphlab.feature_engineering.OneHotEncoder(features=['feature'])
    print 'One-hot encoded:'
    print f

    # We first fit the transformer using the above data.
    f.fit(x)
    print 'Fitted encoder:'
    print f

    # The transform method will add a new column that is the transformed version
    # of the 'word' column.
    x = f.transform(x)
    print 'Applied encoder:'
    print x

    # Get the feature mapping.
    mapping = f['feature_encoding']
    print 'Mapping:'
    print mapping

    # Get the actual word id.
    x['feature_id'] = x['encoded_features'].dict_keys().apply(lambda x: x[0])
    print 'Getting the actual word id:'
    print x

    # Create numpy arrays that contain the data for the sparse matrix.
    i = np.array(x['id'])
    j = np.array(x['feature_id'])
    v = np.array(x['value'])
    width = x['id'].max() + 1
    height = x['feature_id'].max() + 1

    # Create a sparse matrix.
    mat = csr_matrix((v, (i, j)), shape=(width, height))
    print 'Resulting matrix:'
    print mat

    return mat, mapping

In [20]:
sframe_to_scipy(sentences['tf_idf'])

Parameter:
[{'brown': 0.0, 'lazy': 0.6931471805599453, 'jumps': 0.6931471805599453, 'fox': 0.0, 'dog': 0.0, 'quick': 0.0, 'the': 1.3862943611198906, 'over': 0.6931471805599453}, {'outpaces': 0.6931471805599453, 'brown': 0.0, 'fox': 0.0, 'dog': 0.0, 'a': 1.3862943611198906, 'quick': 0.0}]
Creating X1:
+-------------------------------+
|               X1              |
+-------------------------------+
| {'brown': 0.0, 'lazy': 0.6... |
| {'outpaces': 0.69314718055... |
+-------------------------------+
[2 rows x 1 columns]

Adding row number:
+----+-------------------------------+
| id |               X1              |
+----+-------------------------------+
| 0  | {'brown': 0.0, 'lazy': 0.6... |
| 1  | {'outpaces': 0.69314718055... |
+----+-------------------------------+
[2 rows x 2 columns]

Pairs of word and tf-idf:
+----+---------+---------------+
| id | feature |     value     |
+----+---------+---------------+
| 0  |   dog   |      0.0      |
| 0  |   lazy  | 0.69314718056 |
| 0  |

(<2x10 sparse matrix of type '<type 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>, Columns:
 	feature	str
 	category	str
 	index	int
 
 Rows: 10
 
 Data:
 +---------+----------+-------+
 | feature | category | index |
 +---------+----------+-------+
 | feature |   the    |   0   |
 | feature |  jumps   |   1   |
 | feature |    a     |   2   |
 | feature |   over   |   3   |
 | feature | outpaces |   4   |
 | feature |   lazy   |   5   |
 | feature |  quick   |   6   |
 | feature |  brown   |   7   |
 | feature |   dog    |   8   |
 | feature |   fox    |   9   |
 +---------+----------+-------+
 [10 rows x 3 columns])