In [15]:
import numpy as np
    

In [30]:
def get_power(array, power):
    result = np.power(array, power)
    #print array + ' to the ' + power + ': ' + result
    print '%s to the %d: %s' % (str(array), power, str(result))
    return result

In [32]:
def get_sum(array):
    result = np.sum(array)
    print 'sum of %s: %s' % (str(array), str(result))
    return result

In [38]:
def get_subtraction(array1, array2):
    result = np.subtract(array1, array2)
    print 'subtraction of %s and %s: %s' % (str(array1), str(array2), str(result))
    return result

In [34]:
def get_product(array1, array2):
    result = np.multiply(array1, array2)
    print 'product of %s and %s: %s' % (str(array1), str(array2), str(result))
    return result

In [39]:
def get_euclidean_distance(array1, array2):
    sub = get_subtraction(array1, array2)
    power = get_power(sub, 2)
    sum_power = get_sum(power)
    return np.sqrt(sum_power)

In [21]:
def get_cosine_similarity(array1, array2):
    den_1 = np.sqrt(get_sum(get_power(array1, 2)))
    den_2 = np.sqrt(get_sum(get_power(array2, 2)))
    den = den_1 * den_2
    num = get_sum(get_product(array1, array2))
    return num / den

In [3]:
dp_a = [1., 2.]
dp_b = [3., 5.]
dp_c = [5., 4.]

In [35]:
print get_cosine_similarity(dp_a, dp_b)
print get_cosine_similarity(dp_a, dp_c)
print get_cosine_similarity(dp_b, dp_c)

[1.0, 2.0] to the 2: [ 1.  4.]
sum of [ 1.  4.]: 5.0
[3.0, 5.0] to the 2: [  9.  25.]
sum of [  9.  25.]: 34.0
product of [1.0, 2.0] and [3.0, 5.0]: [  3.  10.]
sum of [  3.  10.]: 13.0
0.997054485502
[1.0, 2.0] to the 2: [ 1.  4.]
sum of [ 1.  4.]: 5.0
[5.0, 4.0] to the 2: [ 25.  16.]
sum of [ 25.  16.]: 41.0
product of [1.0, 2.0] and [5.0, 4.0]: [ 5.  8.]
sum of [ 5.  8.]: 13.0
0.9079593845
[3.0, 5.0] to the 2: [  9.  25.]
sum of [  9.  25.]: 34.0
[5.0, 4.0] to the 2: [ 25.  16.]
sum of [ 25.  16.]: 41.0
product of [3.0, 5.0] and [5.0, 4.0]: [ 15.  20.]
sum of [ 15.  20.]: 35.0
0.93742527201


In [40]:
print get_euclidean_distance(dp_a, dp_b)
print get_euclidean_distance(dp_a, dp_c)
print get_euclidean_distance(dp_b, dp_c)

subtraction of [1.0, 2.0] and [3.0, 5.0]: [-2. -3.]
[-2. -3.] to the 2: [ 4.  9.]
sum of [ 4.  9.]: 13.0
3.60555127546
subtraction of [1.0, 2.0] and [5.0, 4.0]: [-4. -2.]
[-4. -2.] to the 2: [ 16.   4.]
sum of [ 16.   4.]: 20.0
4.472135955
subtraction of [3.0, 5.0] and [5.0, 4.0]: [-2.  1.]
[-2.  1.] to the 2: [ 4.  1.]
sum of [ 4.  1.]: 5.0
2.2360679775


In [44]:
import graphlab

important_words = ['the', 'a', 'quick', 'brown', 'fox', 'jumps', 'over', 'lazy', 'dog', 'outpaces']

# Remote punctuation
def remove_punctuation(text):
    import string
    return text.lower().translate(None, string.punctuation) 

import graphlab
from graphlab import SFrame

sentences = graphlab.SFrame({'value':['The quick brown fox jumps over the lazy dog.', 'A quick brown dog outpaces a quick fox.']})
print sentences

sentences['clean'] = sentences['value'].apply(remove_punctuation)

# Split out the words into individual columns
for word in important_words:
    sentences[word] = sentences['clean'].apply(lambda s : s.split().count(word))
    
print sentences

+-------------------------------+
|             value             |
+-------------------------------+
| The quick brown fox jumps ... |
| A quick brown dog outpaces... |
+-------------------------------+
[2 rows x 1 columns]

+-------------------------------+-------------------------------+-----+---+-------+
|             value             |             clean             | the | a | quick |
+-------------------------------+-------------------------------+-----+---+-------+
| The quick brown fox jumps ... | the quick brown fox jumps ... |  2  | 0 |   1   |
| A quick brown dog outpaces... | a quick brown dog outpaces... |  0  | 2 |   2   |
+-------------------------------+-------------------------------+-----+---+-------+
+-------+-----+-------+------+------+-----+----------+
| brown | fox | jumps | over | lazy | dog | outpaces |
+-------+-----+-------+------+------+-----+----------+
|   1   |  1  |   1   |  1   |  1   |  1  |    0     |
|   1   |  1  |   0   |  0   |  0   |  1  |    1  

In [56]:
values = sentences[important_words].to_numpy()
sentence_1 = values[0]
sentence_2 = values[1]
print get_euclidean_distance(sentence_1, sentence_2)
print 1 - get_cosine_similarity(sentence_1, sentence_2)

subtraction of [2 0 1 1 1 1 1 1 1 0] and [0 2 2 1 1 0 0 0 1 1]: [ 2 -2 -1  0  0  1  1  1  0 -1]
[ 2 -2 -1  0  0  1  1  1  0 -1] to the 2: [4 4 1 0 0 1 1 1 0 1]
sum of [4 4 1 0 0 1 1 1 0 1]: 13
3.60555127546
[2 0 1 1 1 1 1 1 1 0] to the 2: [4 0 1 1 1 1 1 1 1 0]
sum of [4 0 1 1 1 1 1 1 1 0]: 11
[0 2 2 1 1 0 0 0 1 1] to the 2: [0 4 4 1 1 0 0 0 1 1]
sum of [0 4 4 1 1 0 0 0 1 1]: 12
product of [2 0 1 1 1 1 1 1 1 0] and [0 2 2 1 1 0 0 0 1 1]: [0 0 2 1 1 0 0 0 1 0]
sum of [0 0 2 1 1 0 0 0 1 0]: 5
0.564805860111
