In [35]:
from __future__ import division
import graphlab
import math
import string
import numpy as np

In [36]:
probabilities = []
probabilities_positive = []
weights = [0, 1]
features = [[1, 2.5], [1, 0.3], [1, 2.8], [1, 0.5]]
output = [1, -1, 1, 1]
scores = np.dot(features, weights)
print scores

[ 2.5  0.3  2.8  0.5]


In [37]:
for i in range(len(scores)):
    probability = 1 / (1 + math.exp(-scores[i]))
    probabilities_positive.append(probability)
    if (output[i]) == -1:
        probability = 1 - probability
    probabilities.append(probability)
print probabilities

[0.9241418199787566, 0.42555748318834097, 0.9426758241011313, 0.6224593312018546]


In [38]:
reduce(lambda x, y: x*y, probabilities)

0.23076514147414118

In [39]:
features_matrix = np.matrix(features)
features_array = features_matrix[:,1]
print features_array

[[ 2.5]
 [ 0.3]
 [ 2.8]
 [ 0.5]]


In [41]:
contributions = []
for i in range(len(features_array)):
    feature_x = features_array[i]
    output_y = output[i]
    indicator = None
    if output_y == -1:
        indicator = 0
    elif output_y == 1:
        indicator = 1
    contribution = feature_x * (indicator - probabilities_positive[i])
    contributions.append(contribution)
sum(contributions)

matrix([[ 0.36659072]])